#!/bin/sh
# FreenetIS-redirection DEB: actions before uninstalling of package

set -e
. /usr/share/debconf/confmodule

NAME=freenetis-redirection

# stop daemon
if [ -x /usr/sbin/invoke-rc.d ]; then
	invoke-rc.d $NAME stop 3>/dev/null || true
else
	/etc/init.d/$NAME stop 3>/dev/null || true
fi

exit 0
